apiVersion: v1
kind: Service
metadata:
  name: {{dns_name}}
spec:
  ports:
  {% for port in ports %}
  - port: {{port['port']}}
    targetPort: {{port['targetPort']}}
  {% endfor %}
  selector:
    {{ selector | to_nice_yaml }}
