apiVersion: v1
kind: Service
metadata:
  name: {{dns_name}}
spec:
  ports:
  {% for p in ports %}
  - port: {{p}}
    targetPort: {{p}}
    name: p-{{p}}
  {% endfor %}
  selector:
    {{ selector | to_nice_yaml }}
