handler: k8s
version: 0.0.1
input:
  dns_name:
    schema: str!
    value:
  C:
    schema: dict!
    value: 
  hash:
    schema: str
    value: null
    computable:
      lang: python
      type: full
      func: "return str(hash(''.join([str(k)+str(v) for k,v in R[R.keys()[0]].iteritems()])))"
