handler: k8s
version: 0.0.1
input:
  dns_name:
    schema: str!
    value:
  image:
    schema: str!
    value:
  container_name:
    schema: str!
    value:
  port:
    schema: str!
    value:
  command:
    schema: str
    value:
  ports:
    schema: []
    value: []
  user:
    schema: str!
    value:
  password:
    schema: str!
    value:
  vhost:
    schema: str!
    value:
  cookie:
    schema: str!
    value:
  replicas:
    schena: int
    value: 1
  labels:
    schema: []
    value: []
