apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{dns_name}}
spec:
  replicas: {{replicas}}
  template:
    metadata:
      labels:
        {{labels | to_nice_yaml}}
    spec:
      containers:
      - image: {{ image }}
        {% if command%}
        command:
        {% for c in command.split() %}
        - {{ c }}
        {% endfor %}
        {% endif %}
        name: {{ container_name }}
        ports:
        {% for p in ports %}
        - containerPort: {{p}}
        {% endfor %}
        env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{user}}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{password}}
            - name: RABBITMQ_DEFAULT_VHOST
              value: {{vhost}}
            - name: RABBITMQ_ERLANG_COOKIE
              value: {{cookie}}
      volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
      volumes:
        - name: rabbitmq-data
          emptyDir: {}
